# Dockerfile for Networked File Store Client - Query

# Use map_base
FROM map_base




# add service files to the working directory
ADD . .

# set command to run server
ENTRYPOINT ["java", "-jar", "networked-file-store-client-query.jar"]

