---
- hosts: all
  become: yes

  # don't try and gather facts until python is installed
  gather_facts: False

  # make sure python is installed and then gather facts
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -qqy --allow-releaseinfo-change update && apt install -qy python3)
    - setup:

  tasks:
    - name: install packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
        - kmod
        - default-jre-headless
        - iftop
        - quagga-ospfd
        - rsync
        - xz-utils
        - python3
        - bridge-utils
        - socat
        - tshark
        - bind9-host
          
    - name: install sysctl ip_forwarding config
      copy:
        src: 99-ip_forwarding.conf
        dest: /etc/sysctl.d/99-ip_forwarding.conf
        owner: root
        mode: 0664
        
    - name: "enable ip forwarding"
      command: sysctl -w net.ipv4.ip_forward=1

    - name: Add map user with sudo privileges
      user:
        name: map
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Copy create swap script
      copy:
        src: create-swap.sh
        dest: /tmp/create-swap.sh
        owner: root
        mode: 0777
    - name: Create swap space
      shell: /tmp/create-swap.sh


- hosts: ncps:clients
  become: yes
  tasks:
    - name: install packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
        - docker.io

    - name: Give map user access to docker
      user:
        name: map
        groups: docker
        append: yes
        
    - name: restart docker
      systemd:
        name: docker
        state: restarted
        
