---
- hosts: all
  become: yes
  tasks:
    - name: install packages that helps ansible function
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
        - acl
        - python3
