---
- hosts: all
  become: yes
  tasks:
    - name: install packages that help ansible function
      apt:
        update_cache: yes
        name:
          - acl
          - python3
      register: result
      until: result is not failed
      retries: 10
