---
- hosts: all
  become: yes
  tasks:
    - name: resolved.conf format
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^[Resolve]'
        line: '[Resolve]'
      
    - name: Use fallback DNS
      lineinfile:
        path: /etc/systemd/resolved.conf
        insertafter: '^[Resolve]'
        regexp: '^DNS='
        line: 'DNS=172.30.0.1'

    - name: reload systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
