- hosts: registry
  become: yes
  tasks:
    - name: Copy images for the registry (DCOMP)
      copy:
        src: /project/map/registry/map_service_images.tar
        dest: /var/lib/map/registry/map_service_images.tar
        owner: root
        mode: 0444       
