- hosts: registry
  become: yes
  tasks:
    - name: Copy images for the registry (Emulab)
      copy:
        src: /proj/a3/map/registry/map_service_images.tar
        dest: /var/lib/map/registry
        owner: root
        mode: 0444       
