- hosts: ncps
  become: yes
  tasks:
    - name: Copy control network assignments  (Emulab)
      copy:
        src: hosts.emulab
        dest: /etc/map/node_control_names
        owner: root
        mode: 0444       
