---
- hosts: clients
  become: yes
  tasks:
    - name: Execute pre-start commands for clients
      become: yes
      shell: java -jar map-client-pre-start.jar
      args: 
        chdir: /var/lib/map/client
      
