- hosts: all
  become: yes
  tasks:
    - name: stop zebra
      systemd:
        name: zebra
        state: stopped
        enabled: no
    - name: stop ospfd
      systemd:
        name: ospfd
        state: stopped
        enabled: no
